ALTER TABLE vouchers ADD COLUMN journal_chars INTEGER NOT NULL DEFAULT 0;
ALTER TABLE vouchers ADD COLUMN journal_seconds INTEGER NOT NULL DEFAULT 0;
ALTER TABLE vouchers ADD COLUMN plan_items INTEGER NOT NULL DEFAULT 0;
ALTER TABLE vouchers ADD COLUMN journal_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE vouchers ADD COLUMN plan_hash TEXT NOT NULL DEFAULT '';
